### ISSUE TITLE
Flowtype

### ISSUE THREAD

**Issue by couto** [archived-codacy/codacy-eslint-legacy#58]
As far as I can tell, ESLint will use some shared configs, including the [eslint-plugin-flowtype](https://github.com/codacy/codacy-eslint/blob/master/src/main/scala/codacy/eslint/ESLint.scala#L141)

However this plugin only works properly if ESLint is using the [babel-eslint](https://github.com/babel/babel-eslint) parser instead of the regular parser, as stated in the [installation instructions](https://github.com/gajus/eslint-plugin-flowtype#installation)

This is relevant because eslint doesn't understand type annotations, rendering Flowtype files useless.

**Comment by rtfpessoa** [comment]
Codacy supports using a configuration file where you can specify all those details.

**Comment by couto** [comment]
@rtfpessoa I'm a bit newbie with Codacy, is there a place where we can find some docs about eslint? (there probably is, but my search skills are totally failing me :) )

**Comment by rtfpessoa** [comment]
There are no specific docs to ESLint. It is mostly automatic. If you add a project and it has an ESLint config file in the root, Codacy will start using it, if you do not have, Codacy will assign default patterns that you can then configure thought the UI.

Basically Codacy either runs with your config file or with the customized patterns in the UI. In your case since you need a custom parser you need to user a configuration file. For more details check here http://eslint.org/docs/user-guide/configuring

**Comment by couto** [comment]
mmm... then definitely something is wrong, but I guess it's out of the scope of this issue. 
Thanks for you time and patience :)

**Comment by rtfpessoa** [comment]
@Couto reach out through support at codacy dot com and it will be easier to understand the exact problem.
